%%%%%%% This is an example file
%%%%%%% Jing Feng (jing.feng@noaa.gov), Oct 10, 2022
path_modtran='/project/rrg-yihuang-ad/binmenja/models/modtran6/bin/linux/';  %% please change this line to your own data directory
file_profile = '/home/binmenja/projects/rrg-yihuang-ad/binmenja/models/modtran6/nsa_analysis/profile_sonde_202002.mat'
load(file_profile)
resolution = 0.1; %cm-1
cloud.qi = []; % NO CLOUD
cloud.ql = [];% NO CLOUD
cloud.z = [];% NO CLOUD
fwhm = resolution./2; % NEED TO READ
v1 = 200;
v2 = 2000;
angle = 180; % 180 IS ZENITH ANGLE SO 180 DEGREES IS GROUND TO SPACE
emis= 0.3; % IMPORTANT   
iLoc = '0';
zt = profile.z(end);
ts = profile.t(1);
mode_sun = 0; % Sun mode -  see table 3.3
disp('modtran6 maker')
%new_tape5_make_cld_profile(path_modtran,profile.nlyr,profile.z,profile.p,profile.t,profile.q,profile.co2,profile.o3,resolution,fwhm,cloud,v1,v2,angle,iLoc,emis,zt,ts, mode_sun, profile.time);%,iLoc,emis,zt,ts);
modtran6_tape5_make_brb(path_modtran,profile.nlyr,profile.z,profile.p,profile.t,profile.q,profile.co2,profile.o3,resolution,fwhm,cloud,v1,v2,angle,iLoc,emis,zt,ts);
%% removes existing tapes
system('rm test_riot.chn');
system('rm test_riot.plt');
system('rm test_riot.tp8');
%% calls modtran6 to run
system([path_modtran,'tp5tojson test_riot.tp5']);
system([path_modtran,'mod6c_cons test_riot.json']); %% *.json is the 'new version' input file generated by the tape5 maker. mod6c_cons is the executable
disp('written')
[wavnum_plt, rad_plt] = read_pltout(strcat(path_modtran,'test_riot.plt'));
plot(wavnum_plt, rad_plt, LineWidth=0.5);
xlabel('Wavenumber');
ylabel('Radiance');
saveas(gca,'test_riot.jpg');
%% read outputsi
%addpath('/home/binmenja/projects/rrg-yihuang-ad/binmenja/models/modtran6/nsa_analysis/')
[wavenum, rad] =read_channels('test_riot.chn',6);  %% mlw.chn is the outputfile; 6 for specifying the version of modtran.
