%%%%%%% This is an example file
%%%%%%% Benjamin Riot--Bretecher (benjamin.riotbretecher@mail.mcgill.ca), March 14, 2024
path_modtran='/project/rrg-yihuang-ad/binmenja/models/modtran6/bin/linux/';  % please change this line to your own data directory
file_profile = '/home/binmenja/projects/rrg-yihuang-ad/binmenja/nsa/example_profile/example.mat'; % please change this line to your own profile file
load(file_profile)
% Assuming the profile variable is named "profile"
format long
resolution = 0.1; %cm-1, line by line resolution
cloud.qi = []; % NO CLOUD
cloud.ql = [];% NO CLOUD
cloud.z = [];% NO CLOUD
fwhm = resolution.*2; 
v1 = 380; % start wavenumber
v2 = 1800; % end wavenumber
angle = 180; % read modtran6_tape5_maker.m for more details
emis= 0; % read modtran6_tape5_maker.m for more details 
iLoc = '0'; 
clear spectra
for i =1:size(profile.z,2) % loop for each profile, assuming the second dimension represents the number of profiles
    clear zt ts z p t q o3 co2 nlyr 
    z = profile.z(:,i);
    p = profile.p(:,i);
    q = profile.q(:,i);
    t = profile.t(:,i);
    nlyr = size(z,1)-1;
    co2 = profile.co2(:,i);
    o3 = profile.o3(:,i).*1000; % has to be in g/kg, here the o3 input was in kg/kg so have to convert
    zt = z(end);
    ts = 0; % ts is the boundary temperature (space) [K]
    mode_sun = 0; % Sun mode -  see table 3.3 of the manual for more details

    modtran6_tape5_maker(path_modtran,nlyr,z,p,t,q,co2,o3,resolution,fwhm,cloud,v1,v2,angle,iLoc,emis,zt,ts); 
    disp('tape5 successfully saved')

    %% removes existing tapes
    system('rm example.plt');
    %system('rm 202002.tp8');

    %% call modtran6 to run
    system([path_modtran,'tp5tojson example.tp5 2> error1.log']);
    system([path_modtran,'mod6c_cons example.json 2> error2.log']); %% *.json is the 'new version' input file generated by the tape5 maker. mod6c_cons is the executable
    disp('written')
    [spectra.wavnum_plt(:,i), spectra.rad_plt(:,i)] = read_pltout(strcat(path_modtran,'example.plt'));
    spectra.wavnum_plt = spectra.wavnum_plt(:,1);
    %spectra.opt_depth(:,i) = read_tape7_brb('example.tp7');
    spectra.date(i) = profile.date(i);
    %[~, ~, ~, ~, ~, ~, ~, ~, ~, ~, spectra.rh(i,:), ~, ~, ~] = read_data_with_header('example.tp6') 
end
save('/home/binmenja/direct/models/modtran6/nsa_analysis/output/example.mat','spectra','-v7.3');

% Uncomment the following lines to plot the results
% plot(spectra.wavnum_plt, spectra.rad_plt, LineWidth=0.5);
% xlabel('Wavenumber');
% ylabel('Radiance');
% saveas(gca,'latest_run.jpg');
% disp('Plot saved! - latest_run.jpg');

